Traceback (most recent call last):
  File "/var/lib/condor/execute/dir_25883/condor_exec.exe", line 165, in <module>
    main(sys.argv[1:])
  File "/var/lib/condor/execute/dir_25883/condor_exec.exe", line 161, in main
    performPlacement(inputfile,outputfile)
  File "/var/lib/condor/execute/dir_25883/condor_exec.exe", line 124, in performPlacement
    pMover.server()
  File "/var/lib/condor/execute/dir_25883/IperfMover.py", line 64, in server
    self.run()
  File "/var/lib/condor/execute/dir_25883/DataMover.py", line 147, in run
    rd.run()
TypeError: run() takes no arguments (1 given)
