Traceback (most recent call last):
  File "/var/opt/condor/execute/dir_13957/condor_exec.exe", line 165, in <module>
    main(sys.argv[1:])
  File "/var/opt/condor/execute/dir_13957/condor_exec.exe", line 161, in main
    performPlacement(inputfile,outputfile)
  File "/var/opt/condor/execute/dir_13957/condor_exec.exe", line 98, in performPlacement
    pChirp.ulog(iam,"error %s" % e.message)
  File "/var/opt/condor/execute/dir_13957/ChirpTools.py", line 20, in ulog
    self.chirp.ulog(logMessage)
  File "/var/opt/condor/execute/dir_13957/CondorTools.py", line 63, in ulog
    raise IDPLException.CondorChirpUlogException(message)
IDPLException.CondorChirpUlogException
